---
steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install'] # Install dependencies
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'test:unit'] # Run unit test
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/gcb-docker-compose:latest', '.'] # Build the docker image wit docker-compose
- name: 'docker/compose:1.15.0'
  args: ['up', '-d'] # Run the application with docker-compose
  env:
  - 'PROJECT_ID=$PROJECT_ID'
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'test:integration'] # Integration test
  env:
  - 'HOST=counter' # name of the running container
  - 'PORT=50051'
images: ['gcr.io/$PROJECT_ID/gcb-docker-compose:latest'] # Push the image to the Container Registry
